### ISSUE TITLE
Seeds dont seem to drop in MP

### ISSUE THREAD

**Issue by Poke5555** [enemeez/simplefarming#1]
im using forge 27.0.51 and simple farming 1.0.1'
seeds drop in my single player world but not on my server.
i can spawn in seeds/crops/items in multiplayer, just not seed drops from breaking grass.

**Comment by enemeez** [comment]
I set up a server on 27.0.50 with version 1.0.1 and the seeds were dropping.

Are you using any other mods that might cause a conflict?

**Comment by Poke5555** [comment]
https://pastebin.com/114LfzTW is my modlist

**Comment by enemeez** [comment]
I am about to release an update for forge 27.0.53. 

If this issue is still occurring, it is temporarily unfixable due to the HarvestDropEvent not being fired for block harvesting. As a result, the loot tables with other mods may conflict. https://github.com/MinecraftForge/MinecraftForge/issues/5828

**Comment by Poke5555** [comment]
still nothing, so i guess its a mod conflict? or because the world was generated without it then SF was added later? idk. the trees still generate in new chunks though, its very strange.

**Comment by enemeez** [comment]
Unfortunately, the whole issue stems around Forge still being in an early build. So a temporary solution, I have made is using wild crops that you can break for seeds. This will be implemented in the next update.
