### ISSUE TITLE
Config option for disabling seed drops from tall grass

### ISSUE THREAD

**Issue by Calendis** [enemeez/simplefarming#146]
I would like to be able to disable all seed drops from tall grass. I'm sure this could be done with a third party mod, but to do it at the source would be nice :)

**Comment by coderepo8593** [comment]
Found a great mod for you. It is regularly updated and not only works with one mod, but any mod you have that adds seeds. This is going to be better than anything a single mod author would do to change their loot tables because except if you wanted to change the ratio of drops from different seeds within a single mod, which is not what you are asking.

https://www.curseforge.com/minecraft/mc-mods/seed-drop-control
