### ISSUE TITLE
Music (Nourish) ignores MC sound settings

### ISSUE THREAD

**Issue by ghost** [enemeez/simplefarming#159]
**Forge Version**
Simple Farming 1.3.5
Forge 36.1.3

**Describe the issue**
The Nourish "music disc" plays on it's own. I have music turned off but it plays anyway.

**Comment by P3pp3rF1y** [comment]
This may be related to Sophisticated Backpacks mobs spawning with jukebox upgrade and this disc in. The issue there is the disc sound ignores the distance from the mob and will always play at the player's position. 

Looks like the exact cause of the issue is the music is in stereo (just checked the ogg and I can see it is). Here's the issue discussed on forge forum: https://forums.minecraftforge.net/topic/73809-solved-1144-custom-music-discs-have-unlimited-attenuation-distance/ 

So converting the music to mono should fix it (if it's related to SBP here anyway)

**Comment by P3pp3rF1y** [comment]
btw, just to be sure tested this in E6 modpack - converted the ogg to mono, put it in simple farming jar and now when I play the disc in jukebox the sound properly gets quieter the further I am from the jukebox.
