### ISSUE TITLE
grass not dropping seeds

### ISSUE THREAD

**Issue by nfr92** [enemeez/simplefarming#34]
Hello, in my world that I just started, grass has not been dropping any seeds and I have it configured correctly in the config file. Do you know the possible reason for this? I have quite a few other mods, I am wondering if one of them is preventing the grass from dropping seeds.

**Comment by enemeez** [comment]
If you can attach a file called latest.log from your minecraft folder, I will be able to see the issue fairly easily.

**Comment by nfr92** [comment]
[latest.log](https://github.com/enemeez/simplefarming/files/3774491/latest.log)

Okay, let me know if this got attached correctly

**Comment by enemeez** [comment]
Just for clarification, are simple farming seeds not dropping? Or are vanilla wheat seeds not dropping too? Additionally, are all drops besides from grass dropping normally?

Could you also provide a modlist for me to check? Sorry for all the questions

**Comment by nfr92** [comment]
Not a problem, I appreciate the help. Simple farming seeds are not dropping at all and minecraft wheat seeds drop rarely, and I am also wondering if they are not dropping normally. I broke down grass across a plains field and only one minecraft wheat seed dropped. Other blocks such as dirt and cobblestone do work, along with other stones and ores, and mobs drop items. 

How can I send a mod list? I currently have 166 mods in the mods folder. It is a lot but I have 24 GB of ram and wanted to see what worked.

**Comment by enemeez** [comment]
166 mods is quite a lot to sift through. Simple Farming is still early in development, but I am fairly confident that the issue with seeds is not caused by my mod as it has been included in some frequently tested mod packs.

If you want to find the potential mods to check, I will tell you how in your latest.log file:

1. In the log file, use ctrl+f to search for key word "parse"
2. If you see anything like "failed to parse loot table", take a note of the mod's name as drops for that specific block are not being put together correctly
3. Otherwise, try to narrow down your mods to the ones that drop seeds and see if any conflicts or errors are occurring

**Comment by nfr92** [comment]
Okay thanks I will give it a shot

**Comment by nfr92** [comment]
So I wanted to let you know that in the version simple farming 1.14.4-1.1.9 I am getting seeds to drop but the latest version does not drop any seeds for me, not sure if the latest version has an issue with that or if its still something on my end

**Comment by enemeez** [comment]
In that version, I was using old seed drop mechanics that were replaced with working loot tables. So, again, it is likely still an issue with loot tables
