### ISSUE TITLE
[1.15.1] Cherry Tree Crash

### ISSUE THREAD

**Issue by NillerMedDild** [enemeez/simplefarming#54]
**Forge Version**
1.15.1-30.0.41

**Mod list (optional)**
https://github.com/NillerMedDild/Enigmatica5/blob/master/CHANGELOG-MODS.md

**Log file (optional)**
https://pastebin.com/Cy7W90jg

**Describe the issue**
Harvesting Cherry Tree leaves crashes the server.

**Comment by enemeez** [comment]
Unfortunately, the log file doesn't tell me much. There is something being done within the fast leaf decay mod where `FruitLeavesBlock`  is casted to a `LeavesBlock` from Minecraft. I can't tell exactly as the github page for that mod doesn't seem to be updated.

However, a goal of mine was to get the leaf decay of my fruit leaves to simulate vanilla instead of being instantly deleted. So perhaps changing around the code and behavior of my leaves will fix this issue.

**Comment by NillerMedDild** [comment]
Worth a shot :D I guess there's not much else to do, when the source code isn't available.
